using System;
using UnityEngine;

namespace ActionCode.InitializationSystem
{
    /// <summary>
    /// Generates and logs a Unique User Session number only when the game initializes.
    /// Only works in a Builds, not in Editor.
    /// </summary>
    public static class UserSessionGenerator
    {
        /// <summary>
        /// The unique Session (generated by Guid) from this user.
        /// </summary>
        public static string Session { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSplashScreen)]
        private static void Initialize()
        {
            if (Application.isEditor) return;

            Session = Guid.NewGuid().ToString();
            Debug.Log($"User session: {Session}");
        }
    }
}